# Generated by Django 5.2.6 on 2025-09-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='airflow_dag_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='schedule_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notebook',
            name='schedule_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notebook',
            name='schedule_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notebook',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
