# Generated by Django 5.2.6 on 2025-09-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notebook_airflow_dag_id_notebook_is_scheduled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAIL', 'Fail')], default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.notebook')),
            ],
        ),
    ]
