# Generated by Django 5.2.6 on 2025-09-20 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notebookrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('schedule_seconds', models.IntegerField(default=0)),
                ('schedule_minutes', models.IntegerField(default=0)),
                ('schedule_hours', models.IntegerField(default=0)),
                ('airflow_dag_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notebook')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='notebooks',
            field=models.ManyToManyField(related_name='schedules', through='core.ScheduleStep', to='core.notebook'),
        ),
    ]
