# Generated by Django 5.2.6 on 2025-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule_schedulestep_schedule_notebooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cron_expression',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
